add step for updating status badge6

diff --git a/.github/workflows/edit_badges.yml b/.github/workflows/edit_badges.yml
--- a/.github/workflows/edit_badges.yml
+++ b/.github/workflows/edit_badges.yml
@@ -58,19 +58,18 @@ jobs:
         shell: bash
         run: |
           set -eu
-          cd ${{ inputs.repo_name }}
+          cd "${{ inputs.repo_name }}"
+
           if [ "${{ inputs.job_status }}" = "success" ]; then
-            sed 's/"#c7b7b7"/"green"/g' assets/blank_status.svg > updated_status.svg
-            sed 's/{{STATUS}}/pass/g' assets/blank_status.svg > updated_status.svg
+              sed 's/"#c7b7b7"/"green"/g; s/{{STATUS}}/pass/g' assets/blank_status.svg > updated_status.svg
           elif [ "${{ inputs.job_status }}" = "failure" ]; then
-            sed 's/"#c7b7b7"/"red"/g' assets/blank_status.svg > updated_status.svg
-            sed 's/{{STATUS}}/fail/g' assets/blank_status.svg > updated_status.svg
+              sed 's/"#c7b7b7"/"red"/g; s/{{STATUS}}/fail/g' assets/blank_status.svg > updated_status.svg
           else
-            echo "Invalid job status. Cannot update status badge."
-            exit 1
+              echo "Invalid job status. Cannot update status badge."
+              exit 1
           fi
 
-          mv updated_status.svg assets/${{ inputs.env_name }}_build_status.svg
+          mv updated_status.svg assets/"${{ inputs.env_name }}"_build_status.svg
 
       - name: Configure git and push commit
         run: |
